### ISSUE TITLE
[HW] Adharsh Jolly

### ISSUE THREAD

**Issue by Adharshjolly** [datastaxdevs/workshop-todo-native-mobile#50]
**Name:** Adharsh Jolly 
**Email:** adharshjolly23@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/adharsh-jolly-30858221b 

Attach the homework screenshot below:
Just a single image of your deployed app on your mobile device via Expo Go or in a browser is fine (note, using Expo Go is the fun way)
-----------------------------------------

[Tap to see the Live demo ](https://aj-codes-todoapp.netlify.app)

![**My Work**](https://user-images.githubusercontent.com/86960153/132091126-1989e282-ab56-4dec-b32b-4cdb2395f2e7.jpg)

**Comment by HadesArchitect** [comment]
Hey **Adharsh Jolly**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/LTyxnnvGQBuVIw8C5VJc4A
